# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

closed_beta_lm_AL_cpp <- function(wts, gamma, y, X, F_reparam, s_hat_reparam, dual_step) {
    .Call('_BICEP_closed_beta_lm_AL_cpp', PACKAGE = 'BICEP', wts, gamma, y, X, F_reparam, s_hat_reparam, dual_step)
}

mirror_descent_REL <- function(wts, delta, gamma, Z_mat, dual_step, mirror_step = 1.0, maxit = 1000L, mirror_eps = 1e-8, tol_type = "fval", vary_step = FALSE, line_search = FALSE, ls_eps = 1e-10, ls_maxit = 1000L, ls_beta = .75) {
    .Call('_BICEP_mirror_descent_REL', PACKAGE = 'BICEP', wts, delta, gamma, Z_mat, dual_step, mirror_step, maxit, mirror_eps, tol_type, vary_step, line_search, ls_eps, ls_maxit, ls_beta)
}

prox_grad_REL <- function(wts_new, Z_mat, gamma_curr, dual_step, delta_inp, q, delta_step = 1.0, maxit = 2000L, outlier_eps = 1e-5, accelerate = TRUE, line_search = TRUE, ls_eps = 1e-12, ls_maxit = 100L, ls_beta = .75) {
    .Call('_BICEP_prox_grad_REL', PACKAGE = 'BICEP', wts_new, Z_mat, gamma_curr, dual_step, delta_inp, q, delta_step, maxit, outlier_eps, accelerate, line_search, ls_eps, ls_maxit, ls_beta)
}

